"""add articles_hashtags associate table

Revision ID: 3e85ab9ca1e6
Revises: 4b94e90df8a5
Create Date: 2023-03-22 20:08:20.106836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e85ab9ca1e6'
down_revision = '4b94e90df8a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_hashtags',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], )
    )
    op.create_unique_constraint(None, 'authors', ['email'])
    op.create_unique_constraint(None, 'authors', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_table('articles_hashtags')
    # ### end Alembic commands ###
